services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  kafka-init-topics:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - kafka
    command:
      - /bin/bash
      - -ec
      - |
        echo "Waiting for Kafka to be ready..."
        cub kafka-ready -b kafka:9092 1 60

        echo "Creating topic search-logs (if missing)..."
        kafka-topics --bootstrap-server kafka:9092 \
          --create --if-not-exists \
          --topic search-logs \
          --replication-factor 1 \
          --partitions 1

        echo "Verifying topic search-logs exists..."
        kafka-topics --bootstrap-server kafka:9092 \
          --describe --topic search-logs

        echo "=== TOPIC search-logs IS READY ==="

  search-trends-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: search-trends
    ports:
      - "8080:8080"
    depends_on:
      kafka:
        condition: service_started
      kafka-init-topics:
        condition: service_completed_successfully
    environment:
      - KAFKA_BROKERS=kafka:9092
      - CONFIG_PATH=config/config.yaml
    volumes:
      - ./config/stop-list.txt:/app/config/stop-list.txt
    restart: on-failure

  traffic-generator:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: generator
    depends_on:
      kafka:
        condition: service_started
      kafka-init-topics:
        condition: service_completed_successfully
    environment:
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_TOPIC=search-logs
      - CONFIG_PATH=config/config.yaml
    restart: on-failure

  prometheus:
    image: prom/prometheus:v3.11.3
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - search-trends-service